export const OBTER_PROJETOS = "OBTER PROJETOS"

export const ALTERAR_PROJETO = "ALTERAR PROJETO"

export const CADASTRAR_PROJETO = "CADASTRAR PROJETO"
export const ACTION_EXCLUIR_PROJETO = "EXCLUIR PROJETO"

export const ACT_OBTER_TAREFAS = "OBTER TAREFAS"
export const ACT_CADASTRAR_TAREFA = "CADASTRAR TAREFA"
export const ACT_ALTERAR_TAREFA = "ALTERAR TAREFA"
export const ACT_REMOVER_TAREFA = "REMOVER TAREFA"